[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Library for building WebSocket servers and clients in Mojo"
name = "mojo-websockets"
platforms = ["linux-64"]
version = "0.1.3"

[dependencies]
max = "*"
