[project]
authors = ["Manuel Saelices <msaelices@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Library for building WebSocket servers and clients in Mojo"
name = "mojo-websockets"
platforms = ["linux-64"]
version = "0.2.0

[dependencies]
max = ">=25.2.0"
