name: Run the testing suite

on:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run the test suite
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          source $HOME/.bash_profile
          pixi run mojo test -I src/ tests/
